version: '3.8'

services:
  ai-triage-server:
    build: .
    container_name: smart_ai_triage
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules # حماية مكتبات الكونتینر من التداخل مع الويندوز
    restart: always